main = "workers-site/index.js"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

# Configure how to serve static files from the dist folder
[site]
bucket = "dist"

[build]
command = "npm run build:prod"
cwd = "."
